## Matrices

In mathematics, a matrix (plural matrices) is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns. Matrices are commonly written in box brackets. The horizontal and vertical lines of entries in a matrix are called rows and columns, respectively. The size of a matrix is defined by the number of rows and columns that it contains. A matrix with $m$ rows and $n$ columns is called an $m\times n$ matrix or $m$-by-$n$
matrix, while $m$ and $n$ are called its dimensions. The dimensions of the following matrix are $2\times 3$
(read “two by three”), because there are two rows and three columns.
 
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}

The individual items (numbers, symbols or expressions) in a matrix are called its elements or entries.

In \texttt{python} matrices can be represented as \texttt{numpy.array}, so the example above will become:

In [17]:
import numpy as np

print (np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


Essentially a \texttt{numpy.array} is a list of lists each one representing a matrix row. Arrays can have any dimension so they can be used to represent also vectors in \texttt{python}. There are two special types of arrays \texttt{zeros} and \texttt{ones} whose name already clarify their meaning:

In [18]:
A = np.zeros(shape=(3, 3))
B = np.ones(shape=(4, 4))

print (A)
print ()
print (B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Adding and Subtracting Matrices
We use matrices to list data or to represent systems. Because the entries are numbers, we can perform operations on matrices. We add or subtract matrices by adding or subtracting corresponding entries.

In order to do this, the entries must correspond. Therefore, addition and subtraction of matrices is only possible when the matrices have the same dimensions.  
Adding matrices is very simple. Just add each element in the first matrix to the corresponding element in the second matrix.

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
+
\begin{bmatrix}
10 & 20 & 30\\
40 & 50 & 60
\end{bmatrix}
=
\begin{bmatrix}
11 & 22 & 33\\
44 & 55 & 66
\end{bmatrix}
$$

As you might guess, subtracting works much the same way except that you subtract instead of adding.

$$
\begin{bmatrix}
10 & 20 & 30\\
40 & 50 & 60
\end{bmatrix}
-
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
=
\begin{bmatrix}
9 & 18 & 27\\
36 & 45 & 54
\end{bmatrix}
$$

Adding and subtracting \texttt{numpy.array} is as easy as that:

In [19]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[10,20,30],[40,50,60]])

print (A+B)
print (B-A)

[[11 22 33]
 [44 55 66]]
[[ 9 18 27]
 [36 45 54]]


### Scalar Multiplication
Multiplying a matrix by a scalar $c$ means you add the matrix to itself $c$ times, or simply multiply each element by that constant.

$$
3 \cdot
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
=
\begin{bmatrix}
3 & 6 & 9 \\
12 & 15 & 18
\end{bmatrix}
$$

Scalar multiplication of \texttt{numpy.array} is:

In [20]:
c = 3
A = np.array([[1,2,3],[4,5,6]])

print (c*A)

[[ 3  6  9]
 [12 15 18]]


### Matrix Multiplication
Matrix multiplication is multiplying every element of each row of the first matrix times every element of each column in the second matrix. When multiplying matrices, the elements of the rows in the first matrix are multiplied with corresponding columns in the second matrix. Each entry of the resultant matrix is computed one at a time.

Let's see with an example:
$$ 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
= ?
$$

First ask: Do the number of columns in the first matrix equal the number of rows in the second ?
If so the product exists.
Then start with producing the product for the first row, first column element. Take the first row of the first matrix and multiply by the first column of the second like this:

$$ 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
(1\cdot 5) + (2\cdot 7) & X \\
X & X
\end{bmatrix}
$$

Continue the pattern with the first row of the first matrix with the second column of the second matrix:

$$ 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
(1\cdot 5) + (2\cdot 7) & (1\cdot 6) + (2\cdot 8)  \\
X & X
\end{bmatrix}
$$

The do the same with the second row of the first matrix and you are done:

$$ 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\cdot
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
=
\begin{bmatrix}
(1\cdot 5) + (2\cdot 7) & (1\cdot 6) + (2\cdot 8)  \\
(3\cdot 5) + (4\cdot 7) & (3\cdot 6) + (4\cdot 8) 
\end{bmatrix}
=
\begin{bmatrix}
19 & 22 \\
43 & 50 
\end{bmatrix}
$$

In \texttt{numpy} array multiplication can be done like this:

In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print (np.dot(A, B))

[[19 22]
 [43 50]]


### The identity matrix 
$[I]$ is defined so that $[A][I]=[A]$, i.e. it is the matrix version of multiplying a number by one.
What matrix has this property? A first guess might be a matrix full of 1s, but that does not work:

$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\begin{bmatrix}
1 & 1 \\
1 & 1
\end{bmatrix}
=
\begin{bmatrix}
3 & 3 \\
7 & 7
\end{bmatrix}
$$

So our initial guess was wrong ! The matrix that does work is a diagonal stretch of 1s, with all other elements being 0:

$$
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

So $
I = \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
$ is the identity matrix for $2\times 2$ matrices.
 
The \texttt{numpy} equivalent of the identity matrix is given by \texttt{numpy.identity(n)} with n the dimension of the matrix. So for example:

In [22]:
A = np.array([[1,2],[3,4]])
I = np.identity(2)

print (A)
print ()
print (np.dot(A, I))

[[1 2]
 [3 4]]

[[1. 2.]
 [3. 4.]]


### Matrix Equations
Matrices can be used to compactly write and work with systems of multiple linear equations.
As we have learned in previous sections, matrices can be manipulated in any way that a normal equation can be. This is very helpful when we start to work with systems of equations. It is helpful to understand how to organize matrices to solve these systems.

### Writing a System of Equations with Matrices
It is possible to solve this system using the elimination or substitution method, but it is also possible to do it with a matrix operation. Before we start setting up the matrices, it is important to do the following:

* make sure that all of the equations are written in a similar manner, meaning the variables need to all be in the same order;
* make sure that one side of the equation is only variables and their coefficients, and the other side is just constants;

Solving a system of linear equations using the inverse of a matrix requires the definition of two new matrices: 
$X$ is the matrix representing the variables of the system, and $B$ is the matrix representing the constants. Using matrix multiplication, we may define a system of equations with the same number of equations as variables as:

$$ A\cdot X = B$$

where $A$ is the coefficient matrix, $X$ is the variable matrix, and $B$ is the constant matrix.
Given the system:

$$
\begin{cases}
x + 8y = 7 \\
2x − 8y = −3
\end{cases}
$$

The corresponding matrices are then:

$$
A=
\begin{bmatrix}
1 & 8\\
2 & −8
\end{bmatrix}
;
X=
\begin{bmatrix}
x\\
y
\end{bmatrix}
;
A=
\begin{bmatrix}
7\\
-3
\end{bmatrix}
$$

Thus, to solve a system $AX=B$, for $X$, multiply both sides by the inverse of $A$ and we shall obtain the solution:

$$A^{-1}AX=A^{-1}B \implies X = A^{-1}B $$

Provided the inverse $A^{-1}$ exists, this formula will solve the system.
If the coefficient matrix is not invertible, the system could be inconsistent and have no solution, or be dependent and have infinitely many solutions.

### The Inverse of a Matrix
The inverse of matrix $A$ is $A^{-1}$, and is defined by the property: 

$$ AA^{-1}=I $$

Hence the matrix $B$ is the inverse of the matrix $A$ if when multiplied together, $A\cdot B$ gives the identity matrix.
Using the definition let's try to find the inverse of:

$$
\begin{bmatrix}
3 & 4\\
5 & 6
\end{bmatrix}
$$

First, let the following be true:

$$
\begin{bmatrix}
3 & 4\\
5 & 6
\end{bmatrix}
\begin{bmatrix}
a & b\\
c & d
\end{bmatrix}
=
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
$$

When multiplying this mystery matrix by our original matrix, the result is 

$$
\begin{bmatrix}
3a+4c & 3b+4d\\
5a+6c & 5b+6d
\end{bmatrix}
=
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
$$

For two matrices to be equal, every element in the left must equal its corresponding element on the right. So, for these two matrices to equal each other:

$$
\begin{cases}
3a+4c=1\\
3b+4d=0\\
5a+6c=0\\
5b+6d=1
\end{cases}
$$

Solving this simple system we get the following result:

$$
\begin{cases}
a=−3\\
b=2\\
c=2.5\\
d=−1.5
\end{cases}
$$

Having solved for the four variables, the result is the inverse 

$$
\begin{bmatrix}
−3 & 2\\
2.5 & −1.5
\end{bmatrix}
$$

The quick check to be sure it is correct is to multiply it by the original matrix and see if the identify matrix results, this is left as an exercise to the reader.

The \texttt{linalg.inv()} function can be used to find the inverse of a matrix in \texttt{python}:

In [23]:
from numpy.linalg import inv

A = np.array([[3,4],[5,6]])
print (inv(A))

[[-3.   2. ]
 [ 2.5 -1.5]]



### Solving Systems of Equations Using Matrix Inverses
A system of equations can be readily solved using the concepts of the inverse matrix and matrix multiplication.  

#### Solve the following system of linear equations:
$$
\begin{cases}
x+2y−z=11\\
2x−y+3z=7\\
7x−3y−2z=2
\end{cases}
$$

Set up the three necesary matrices: 

$$
A=
\begin{bmatrix}
1 & 2 & −1 \\ 
2 & −1 & 3 \\
7 & −3 & −2
\end{bmatrix}
;
B=
\begin{bmatrix}
11\\
7\\
2
\end{bmatrix}
;
X=
\begin{bmatrix}
x\\
y \\ 
z
\end{bmatrix}
$$

Since to solve this system we have to find the inverse matrix of $A$ and multiply it to $B$ we have all the ingredients to do it in \texttt{python}:

In [24]:
A = np.array([[1,2,-1],[2,-1,3],[7,-3,-2]])
B = np.array([11,7,2])

A_inv = inv(A)
sol = np.dot(A_inv, B)

print (sol)

[3. 5. 2.]


So the solution of the system is:
$$
\begin{cases}
x=3\\
y=5\\
z=2
\end{cases}
$$